In [9]:
import pandas as pd

df = pd.read_csv("C:\\Users\\91766\\Downloads\\airline_booking_dataset\\1_airports.csv")
df

,airport_code,airport_name,city,country,timezone
0,DEL,Indira Gandhi International,Delhi,India,Asia/Kolkata
1,BOM,Chhatrapati Shivaji Maharaj Intl,Mumbai,India,Asia/Kolkata
2,BLR,Kempegowda International,Bengaluru,India,Asia/Kolkata
3,MAA,Chennai International,Chennai,India,Asia/Kolkata
4,HYD,Rajiv Gandhi International,Hyderabad,India,Asia/Kolkata
5,CCU,Netaji Subhas Chandra Bose Intl,Kolkata,India,Asia/Kolkata
6,JFK,John F. Kennedy International,New York,USA,America/New_York
7,LAX,Los Angeles International,Los Angeles,USA,America/Los_Angeles
8,LHR,Heathrow,London,UK,Europe/London
9,CDG,Charles de Gaulle,Paris,France,Europe/Paris
10,DXB,Dubai International,Dubai,UAE,Asia/Dubai
11,SIN,Changi,Singapore,Singapore,Asia/Singapore
12,NRT,Narita International,Tokyo,Japan,Asia/Tokyo
13,SYD,Kingsford Smith,Sydney,Australia,Australia/Sydney
14,FRA,Frankfurt Airport,Frankfurt,Germany,Europe/Berlin

In [10]:
print(df.shape)

(15, 5)

In [11]:
df.head()

,airport_code,airport_name,city,country,timezone
0,DEL,Indira Gandhi International,Delhi,India,Asia/Kolkata
1,BOM,Chhatrapati Shivaji Maharaj Intl,Mumbai,India,Asia/Kolkata
2,BLR,Kempegowda International,Bengaluru,India,Asia/Kolkata
3,MAA,Chennai International,Chennai,India,Asia/Kolkata
4,HYD,Rajiv Gandhi International,Hyderabad,India,Asia/Kolkata

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   airport_code  15 non-null     object
 1   airport_name  15 non-null     object
 2   city          15 non-null     object
 3   country       15 non-null     object
 4   timezone      15 non-null     object
dtypes: object(5)
memory usage: 732.0+ bytes

In [13]:
print(df.columns.tolist())

['airport_code', 'airport_name', 'city', 'country', 'timezone']

In [14]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")
df.columns

Index(['airport_code', 'airport_name', 'city', 'country', 'timezone'], dtype='object')

In [15]:
df.isnull().sum()

airport_code    0
airport_name    0
city            0
country         0
timezone        0
dtype: int64

In [17]:
text_cols = df.select_dtypes(include = "object").columns
for c in text_cols:
    df[c] = df[c].str.strip()

text_cols

Index(['airport_code', 'airport_name', 'city', 'country', 'timezone'], dtype='object')

In [18]:
print("Full duplicate rows: ", df.duplicated().sum())
print("Duplicate airport codes: ", df["airport_code"].duplicated().sum())
df = df.drop_duplicates()
df = df.drop_duplicates(subset = "airport_code")

Full duplicate rows:  0
Duplicate airport codes:  0

In [19]:
df["airport_code"] = df["airport_code"].str.upper()
print(df["airport_code"].str.match(r"^[A-Z]{3}$").all())

True

In [21]:
print(df["country"].unique())
print()
print(df["timezone"].unique())

['India' 'USA' 'UK' 'France' 'UAE' 'Singapore' 'Japan' 'Australia'
 'Germany']

['Asia/Kolkata' 'America/New_York' 'America/Los_Angeles' 'Europe/London'
 'Europe/Paris' 'Asia/Dubai' 'Asia/Singapore' 'Asia/Tokyo'
 'Australia/Sydney' 'Europe/Berlin']

In [23]:
print(df["city"].duplicated().sum(), 
df["airport_name"].duplicated().sum())

0 0

In [24]:
print(df.shape)
print()
print(df.isnull().sum().sum())
df

(15, 5)

0

,airport_code,airport_name,city,country,timezone
0,DEL,Indira Gandhi International,Delhi,India,Asia/Kolkata
1,BOM,Chhatrapati Shivaji Maharaj Intl,Mumbai,India,Asia/Kolkata
2,BLR,Kempegowda International,Bengaluru,India,Asia/Kolkata
3,MAA,Chennai International,Chennai,India,Asia/Kolkata
4,HYD,Rajiv Gandhi International,Hyderabad,India,Asia/Kolkata
5,CCU,Netaji Subhas Chandra Bose Intl,Kolkata,India,Asia/Kolkata
6,JFK,John F. Kennedy International,New York,USA,America/New_York
7,LAX,Los Angeles International,Los Angeles,USA,America/Los_Angeles
8,LHR,Heathrow,London,UK,Europe/London
9,CDG,Charles de Gaulle,Paris,France,Europe/Paris
10,DXB,Dubai International,Dubai,UAE,Asia/Dubai
11,SIN,Changi,Singapore,Singapore,Asia/Singapore
12,NRT,Narita International,Tokyo,Japan,Asia/Tokyo
13,SYD,Kingsford Smith,Sydney,Australia,Australia/Sydney
14,FRA,Frankfurt Airport,Frankfurt,Germany,Europe/Berlin

In [26]:
import os
out_dir = r"C:\Users\91766\Downloads\cleaned_data"
os.makedirs(out_dir, exist_ok=True)

df.to_csv(os.path.join(out_dir, "1_airports_clean.csv"), index=False)
print("Saved:", len(df), "rows")

Saved: 15 rows