In [2]:
import pandas as pd 
path = r"C:\Users\91766\Downloads\airline_booking_dataset\2_airplanes.csv"
df = pd.read_csv(path, dtype = {"airplane_code": str})
df

  airplane_code                    model  range_km  speed_kmh  seat_capacity
0           32N           Airbus A320neo      6500        830            166
1           339       Airbus A330-900neo     13300        870            281
2           351         Airbus A350-1000     16700        913            325
3           77W         Boeing 777-300ER     14600        905            404
4           789  Boeing 787-9 Dreamliner     14000        913            257
5           7M7         Boeing 737 MAX 7      7000        840            160
6           CR7        Bombardier CRJ700      3100        829             70
7           E70             Embraer E170      4000        800             78
8          A21N           Airbus A321neo      7400        828            220
9          B38M         Boeing 737 MAX 8      6570        839            178

In [4]:
print(df.shape)
df

(10, 5)

  airplane_code                    model  range_km  speed_kmh  seat_capacity
0           32N           Airbus A320neo      6500        830            166
1           339       Airbus A330-900neo     13300        870            281
2           351         Airbus A350-1000     16700        913            325
3           77W         Boeing 777-300ER     14600        905            404
4           789  Boeing 787-9 Dreamliner     14000        913            257
5           7M7         Boeing 737 MAX 7      7000        840            160
6           CR7        Bombardier CRJ700      3100        829             70
7           E70             Embraer E170      4000        800             78
8          A21N           Airbus A321neo      7400        828            220
9          B38M         Boeing 737 MAX 8      6570        839            178

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   airplane_code  10 non-null     object
 1   model          10 non-null     object
 2   range_km       10 non-null     int64
 3   speed_kmh      10 non-null     int64
 4   seat_capacity  10 non-null     int64
dtypes: int64(3), object(2)
memory usage: 532.0+ bytes

In [7]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")
df.columns

Index(['airplane_code', 'model', 'range_km', 'speed_kmh', 'seat_capacity'], dtype='object')

In [8]:
print(df.isnull().sum())

airplane_code    0
model            0
range_km         0
speed_kmh        0
seat_capacity    0
dtype: int64

In [9]:
for c in ["airplane_code", "model"]:
    df[c] = df[c].str.strip()

In [10]:
print("Full duplicated rows: ", df.duplicated().sum())
print("Duplicate airplane codes: ", df["airplane_code"].duplicated().sum())
print("Duplicate models: ", df["model"].duplicated().sum())
df = df.drop_duplicates().drop_duplicates(subset = "airplane_code")

Full duplicated rows:  0
Duplicate airplane codes:  0
Duplicate models:  0

In [12]:
df["airplane_code"] = df["airplane_code"].str.upper()
df["airplane_code"]

0     32N
1     339
2     351
3     77W
4     789
5     7M7
6     CR7
7     E70
8    A21N
9    B38M
Name: airplane_code, dtype: object

In [13]:
print(df["airplane_code"].str.match(r"^[A-Z-9]{3,4}$").all())

False

In [14]:
num_cols = ["range_km", "speed_kmh", "seat_capacity"]
print((df[num_cols] <= 0).sum())

range_km         0
speed_kmh        0
seat_capacity    0
dtype: int64

In [15]:
df[num_cols].describe()

           range_km   speed_kmh  seat_capacity
count     10.000000   10.000000      10.000000
mean    9317.000000  856.700000     213.900000
std     4849.513263   40.770496     105.695001
min     3100.000000  800.000000      70.000000
25%     6517.500000  829.250000     161.500000
50%     7200.000000  839.500000     199.000000
75%    13825.000000  896.250000     275.000000
max    16700.000000  913.000000     404.000000

In [17]:
print(df.shape, df.isnull().sum().sum())
print()
df

(10, 5) 0

  airplane_code                    model  range_km  speed_kmh  seat_capacity
0           32N           Airbus A320neo      6500        830            166
1           339       Airbus A330-900neo     13300        870            281
2           351         Airbus A350-1000     16700        913            325
3           77W         Boeing 777-300ER     14600        905            404
4           789  Boeing 787-9 Dreamliner     14000        913            257
5           7M7         Boeing 737 MAX 7      7000        840            160
6           CR7        Bombardier CRJ700      3100        829             70
7           E70             Embraer E170      4000        800             78
8          A21N           Airbus A321neo      7400        828            220
9          B38M         Boeing 737 MAX 8      6570        839            178

In [18]:
import os
out_dir = r"C:\Users\91766\Downloads\cleaned_data"
os.makedirs(out_dir, exist_ok=True)

df.to_csv(os.path.join(out_dir, "2_airplanes_clean.csv"), index=False)
print("Saved:", len(df), "rows")

Saved: 10 rows