In [1]:
import pandas as pd

path = r"C:\Users\91766\Downloads\airline_booking_dataset\5_bookings.csv"
df = pd.read_csv(path, dtype = {"book_ref": str})
df

     book_ref            book_date  total_amount
0      OHBVRP  2025-10-27 07:12:00      30124.49
1      OIVGRV  2025-07-20 01:21:00       3724.43
2      IFLBCB  2025-11-19 22:27:00      93112.80
3      FNOGMB  2025-09-11 23:37:00      57817.24
4      JMTPSI  2025-10-11 09:02:00      47849.68
...       ...                  ...           ...
2995   DTPWGY  2025-08-19 17:28:00      28717.50
2996   IUWIZX  2025-03-27 04:31:00      67961.35
2997   USRUBM  2025-09-19 10:47:00      85171.73
2998   ZIEWFQ  2025-05-24 17:40:00      34237.33
2999   VLBOML  2025-10-29 13:23:00      76287.43

[3000 rows x 3 columns]

In [2]:
print(df.shape)

(3000, 3)

In [3]:
df.head()

  book_ref            book_date  total_amount
0   OHBVRP  2025-10-27 07:12:00      30124.49
1   OIVGRV  2025-07-20 01:21:00       3724.43
2   IFLBCB  2025-11-19 22:27:00      93112.80
3   FNOGMB  2025-09-11 23:37:00      57817.24
4   JMTPSI  2025-10-11 09:02:00      47849.68

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   book_ref      3000 non-null   object
 1   book_date     3000 non-null   object
 2   total_amount  3000 non-null   float64
dtypes: float64(1), object(2)
memory usage: 70.4+ KB

In [6]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")
df.columns

Index(['book_ref', 'book_date', 'total_amount'], dtype='object')

In [7]:
print(df.isnull().sum())

book_ref        0
book_date       0
total_amount    0
dtype: int64

In [9]:
df["book_ref"] = df["book_ref"].str.strip().str.upper()
df["book_ref"]

0       OHBVRP
1       OIVGRV
2       IFLBCB
3       FNOGMB
4       JMTPSI
         ...
2995    DTPWGY
2996    IUWIZX
2997    USRUBM
2998    ZIEWFQ
2999    VLBOML
Name: book_ref, Length: 3000, dtype: object

In [10]:
df["book_date"] = pd.to_datetime(df["book_date"], errors = "coerce")
print(df["book_date"].isnull().sum())
print(df["book_date"].min(), "->", df["book_date"].max())

0
2025-01-01 00:39:00 -> 2025-12-31 19:58:00

In [11]:
print("Full duplicate rows: ", df.duplicated().sum())
print("Duplicate book_ref: ", df["book_ref"].duplicated().sum())
df = df.drop_duplicates().drop_duplicates(subset = "book_ref")

Full duplicate rows:  0
Duplicate book_ref:  0

In [12]:
print(df["book_ref"].str.match(r"^[A-Z-9]{6}$").all())

True

In [13]:
print("Zero or negative amounts: ", (df["total_amount"] <= 0).sum())
df["total_amount"].describe().round(2)

Zero or negative amounts:  0

count     3000.00
mean     49302.45
std      26812.43
min       3000.87
25%      26120.44
50%      50276.20
75%      72325.02
max      94973.00
Name: total_amount, dtype: float64

In [15]:
q1, q3 = df["total_amount"].quantile([0.25, 0.75])
iqr = q3 - q1
outliers = df[(df["total_amount"] > q3 + 1.5*iqr) | (df["total_amount"] < q1 - 1.5*iqr)]
print("outliers: ", len(outliers))

outliers:  0

In [17]:
df["total_amount"] = df["total_amount"].round(2)
df["total_amount"]

0       30124.49
1        3724.43
2       93112.80
3       57817.24
4       47849.68
          ...
2995    28717.50
2996    67961.35
2997    85171.73
2998    34237.33
2999    76287.43
Name: total_amount, Length: 3000, dtype: float64

In [18]:
print(df.shape, df.isnull().sum().sum())

(3000, 3) 0

In [19]:
df.dtypes

book_ref                object
book_date       datetime64[ns]
total_amount           float64
dtype: object

In [20]:
import os
out_dir = r"C:\Users\91766\Downloads\cleaned_data"
os.makedirs(out_dir, exist_ok=True)

df.to_csv(os.path.join(out_dir, "5_bookings_clean.csv"),
          index=False, date_format="%Y-%m-%d %H:%M:%S", float_format="%.2f")
print("Saved:", len(df), "rows")

Saved: 3000 rows