In [3]:
import pandas as pd
path = r"C:\Users\91766\Downloads\airline_booking_dataset\4_flights.csv"
df = pd.read_csv(path, dtype = {"flight_no": str,  "airplane_code": str})
df

,flight_id,flight_no,airplane_code,departure_airport,arrival_airport,scheduled_departure,scheduled_arrival,actual_departure,actual_arrival,status
0,1,AI859,32N,DXB,BOM,2025-05-21 07:15:00,2025-05-21 10:03:00,NaN,NaN,Scheduled
1,2,AI704,339,SIN,LHR,2025-08-05 01:00:00,2025-08-05 03:12:00,NaN,NaN,Scheduled
2,3,AI303,A21N,CDG,DEL,2025-11-29 22:45:00,2025-11-30 02:39:00,2025-11-29 23:26:00,2025-11-30 02:29:00,Arrived
3,4,AI814,351,NRT,FRA,2025-08-05 10:30:00,2025-08-05 13:30:00,2025-08-05 10:41:00,2025-08-05 13:33:00,Arrived
4,5,AI467,339,BOM,JFK,2025-06-26 19:30:00,2025-06-27 07:00:00,2025-06-26 19:54:00,2025-06-27 07:05:00,Arrived
...,...,...,...,...,...,...,...,...,...,...
895,896,AI275,32N,JFK,BOM,2025-12-02 15:45:00,2025-12-03 01:45:00,2025-12-02 16:22:00,2025-12-03 02:37:00,Arrived
896,897,AI469,B38M,HYD,CDG,2025-12-20 21:45:00,2025-12-21 09:15:00,NaN,NaN,Scheduled
897,898,AI214,77W,BLR,DEL,2025-01-09 22:15:00,2025-01-10 10:27:00,NaN,NaN,Scheduled
898,899,AI546,77W,DXB,BLR,2025-11-17 17:15:00,2025-11-17 19:21:00,2025-11-17 17:14:00,2025-11-17 20:11:00,Arrived
899,900,AI270,339,JFK,DEL,2025-03-20 23:45:00,2025-03-21 13:15:00,2025-03-21 00:30:00,2025-03-21 14:02:00,Departed

In [4]:
print(df.shape)

(900, 10)

In [5]:
df.head()

,flight_id,flight_no,airplane_code,departure_airport,arrival_airport,scheduled_departure,scheduled_arrival,actual_departure,actual_arrival,status
0,1,AI859,32N,DXB,BOM,2025-05-21 07:15:00,2025-05-21 10:03:00,NaN,NaN,Scheduled
1,2,AI704,339,SIN,LHR,2025-08-05 01:00:00,2025-08-05 03:12:00,NaN,NaN,Scheduled
2,3,AI303,A21N,CDG,DEL,2025-11-29 22:45:00,2025-11-30 02:39:00,2025-11-29 23:26:00,2025-11-30 02:29:00,Arrived
3,4,AI814,351,NRT,FRA,2025-08-05 10:30:00,2025-08-05 13:30:00,2025-08-05 10:41:00,2025-08-05 13:33:00,Arrived
4,5,AI467,339,BOM,JFK,2025-06-26 19:30:00,2025-06-27 07:00:00,2025-06-26 19:54:00,2025-06-27 07:05:00,Arrived

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 900 entries, 0 to 899
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   flight_id            900 non-null    int64
 1   flight_no            900 non-null    object
 2   airplane_code        900 non-null    object
 3   departure_airport    900 non-null    object
 4   arrival_airport      900 non-null    object
 5   scheduled_departure  900 non-null    object
 6   scheduled_arrival    900 non-null    object
 7   actual_departure     444 non-null    object
 8   actual_arrival       444 non-null    object
 9   status               900 non-null    object
dtypes: int64(1), object(9)
memory usage: 70.4+ KB

In [8]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')
df.columns

Index(['flight_id', 'flight_no', 'airplane_code', 'departure_airport',
       'arrival_airport', 'scheduled_departure', 'scheduled_arrival',
       'actual_departure', 'actual_arrival', 'status'],
      dtype='object')

In [9]:
print(df.isnull().sum())

flight_id                0
flight_no                0
airplane_code            0
departure_airport        0
arrival_airport          0
scheduled_departure      0
scheduled_arrival        0
actual_departure       456
actual_arrival         456
status                   0
dtype: int64

In [10]:
print(df[df["actual_departure"].isnull()]["status"].value_counts())

status
Scheduled    289
On Time       89
Delayed       35
Cancelled     24
Boarding      19
Name: count, dtype: int64

In [11]:
for c in ["flight_no", "airplane_code", "departure_airport", "arrival_airport", "status"]:
    df[c] = df[c].str.strip()

df["flight_no"] = df["flight_no"].str.upper()
df["flight_no"]

0      AI859
1      AI704
2      AI303
3      AI814
4      AI467
       ...
895    AI275
896    AI469
897    AI214
898    AI546
899    AI270
Name: flight_no, Length: 900, dtype: object

In [12]:
df["airplane_code"] = df["airplane_code"].str.upper()
df["airplane_code"]

0       32N
1       339
2      A21N
3       351
4       339
       ...
895     32N
896    B38M
897     77W
898     77W
899     339
Name: airplane_code, Length: 900, dtype: object

In [14]:
df["departure_airport"] = df["departure_airport"].str.upper()
df["departure_airport"]

0      DXB
1      SIN
2      CDG
3      NRT
4      BOM
      ...
895    JFK
896    HYD
897    BLR
898    DXB
899    JFK
Name: departure_airport, Length: 900, dtype: object

In [15]:
df["arrival_airport"] = df["arrival_airport"].str.upper()
df["arrival_airport"]

0      BOM
1      LHR
2      DEL
3      FRA
4      JFK
      ...
895    BOM
896    CDG
897    DEL
898    BLR
899    DEL
Name: arrival_airport, Length: 900, dtype: object

In [17]:
df["status"] = df["status"].str.title()
df["status"]

0      Scheduled
1      Scheduled
2        Arrived
3        Arrived
4        Arrived
         ...
895      Arrived
896    Scheduled
897    Scheduled
898      Arrived
899     Departed
Name: status, Length: 900, dtype: object

In [18]:
date_cols = ["scheduled_departure", "scheduled_arrival", "actual_departure", "actual_arrival"]
for c in date_cols:
    df[c] = pd.to_datetime(df[c], errors = "coerce")
print(df[date_cols].isnull().sum())

scheduled_departure      0
scheduled_arrival        0
actual_departure       456
actual_arrival         456
dtype: int64

In [20]:
print("Full duplicate rows: ", df.duplicated().sum())
print("Duplicate flight_id: ", df["flight_id"].duplicated().sum())
print("Duplicate flight_no: ", df["flight_no"].duplicated().sum())
df = df.drop_duplicates().drop_duplicates(subset = "flight_id")

Full duplicate rows:  0
Duplicate flight_id:  0
Duplicate flight_no:  331

In [21]:
print(df["flight_no"].str.match("^[A-Z]{2}\d{3,4}$").all())

True

In [22]:
print(df["status"].value_counts())

status
Arrived      431
Scheduled    289
On Time       89
Delayed       35
Cancelled     24
Boarding      19
Departed      13
Name: count, dtype: int64

In [23]:
print("Arrival not after departure: ", (df["scheduled_arrival"] <= df["scheduled_departure"]).sum())
print("Same arrival and departure airport: ", (df["departure_airport"] == df["arrival_airport"]).sum())
print("Actual arrival before actual departure: ", (df["actual_arrival"] < df["actual_departure"]).sum())

Arrival not after departure:  0
Same arrival and departure airport:  0
Actual arrival before actual departure:  0

In [24]:
duration_hr = (df["scheduled_arrival"] - df["scheduled_departure"]).dt.total_seconds() / 3600
print(duration_hr.describe().round(2))

count    900.00
mean       7.41
std        3.75
min        1.00
25%        4.30
50%        7.20
75%       10.60
max       14.00
dtype: float64

In [25]:
delay_min = (df["actual_departure"] - df["scheduled_departure"]).dt.total_seconds() / 60
print(delay_min.describe().round(1))

count    444.0
mean      17.0
std       15.9
min      -10.0
25%        4.0
50%       16.0
75%       31.0
max       45.0
dtype: float64

In [26]:
airports = pd.read_csv(r"C:\Users\91766\Downloads\cleaned_data\1_airports_clean.csv")
airplanes = pd.read_csv(r"C:\Users\91766\Downloads\cleaned_data\2_airplanes_clean.csv")

bad_dep = ~df["departure_airport"].isin(airports["airport_code"])
bad_arr = ~df["arrival_airport"].isin(airports["airport_code"])
bad_pl = ~df["airplane_code"].isin(airplanes["airplane_code"])
print(bad_dep.sum(), bad_arr.sum(), bad_pl.sum())
df = df[~(bad_dep | bad_arr | bad_pl)]

0 0 0

In [27]:
print(df.shape)

(900, 10)

In [28]:
print(df.isnull().sum())

flight_id                0
flight_no                0
airplane_code            0
departure_airport        0
arrival_airport          0
scheduled_departure      0
scheduled_arrival        0
actual_departure       456
actual_arrival         456
status                   0
dtype: int64

In [29]:
import os
out_dir = r"C:\Users\91766\Downloads\cleaned_data"
os.makedirs(out_dir, exist_ok=True)

df.to_csv(os.path.join(out_dir, "4_flights_clean.csv"),
          index=False, date_format="%Y-%m-%d %H:%M:%S")
print("Saved:", len(df), "rows")

Saved: 900 rows