In [2]:
import pandas as pd 
path = r"C:\Users\91766\Downloads\airline_booking_dataset\6_tickets.csv"
df = pd.read_csv(path, dtype = {"ticket_no":str, "book_ref": str, "passenger_id":str})
df

          ticket_no book_ref  passenger_id    passenger_name  outbound
0     1000000000000   OHBVRP  CN 099613273     Jackie Morgan     False
1     1000000000001   OIVGRV  AL 262446704      Brandon Cruz      True
2     1000000000002   IFLBCB  KG 715160252   Michael Flowers      True
3     1000000000003   FNOGMB  GX 660464197      Jesse Tucker     False
4     1000000000004   FNOGMB  VT 512686120  Michelle Richard     False
...             ...      ...           ...               ...       ...
4800  1000000004800   USRUBM  QL 541572397   Heather Sanchez      True
4801  1000000004801   USRUBM  WT 589199597     John Campbell      True
4802  1000000004802   ZIEWFQ  LP 465631603   Gabriel Andrews      True
4803  1000000004803   VLBOML  IB 489789417  Kristen Lawrence      True
4804  1000000004804   VLBOML  TM 882808231     Melissa Kelly     False

[4805 rows x 5 columns]

In [3]:
print(df.shape)

(4805, 5)

In [4]:
df.head

<bound method NDFrame.head of           ticket_no book_ref  passenger_id    passenger_name  outbound
0     1000000000000   OHBVRP  CN 099613273     Jackie Morgan     False
1     1000000000001   OIVGRV  AL 262446704      Brandon Cruz      True
2     1000000000002   IFLBCB  KG 715160252   Michael Flowers      True
3     1000000000003   FNOGMB  GX 660464197      Jesse Tucker     False
4     1000000000004   FNOGMB  VT 512686120  Michelle Richard     False
...             ...      ...           ...               ...       ...
4800  1000000004800   USRUBM  QL 541572397   Heather Sanchez      True
4801  1000000004801   USRUBM  WT 589199597     John Campbell      True
4802  1000000004802   ZIEWFQ  LP 465631603   Gabriel Andrews      True
4803  1000000004803   VLBOML  IB 489789417  Kristen Lawrence      True
4804  1000000004804   VLBOML  TM 882808231     Melissa Kelly     False

[4805 rows x 5 columns]>

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4805 entries, 0 to 4804
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ticket_no       4805 non-null   object
 1   book_ref        4805 non-null   object
 2   passenger_id    4805 non-null   object
 3   passenger_name  4805 non-null   object
 4   outbound        4805 non-null   bool
dtypes: bool(1), object(4)
memory usage: 155.0+ KB

In [6]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")
df.columns

Index(['ticket_no', 'book_ref', 'passenger_id', 'passenger_name', 'outbound'], dtype='object')

In [7]:
print(df.isnull().sum())

ticket_no         0
book_ref          0
passenger_id      0
passenger_name    0
outbound          0
dtype: int64

In [8]:
for c in ["ticket_no", "book_ref", "passenger_id", "passenger_name"]:
    df[c] = df[c].str.strip()

df["book_ref"] = df["book_ref"].str.upper()
df["book_ref"]

0       OHBVRP
1       OIVGRV
2       IFLBCB
3       FNOGMB
4       FNOGMB
         ...
4800    USRUBM
4801    USRUBM
4802    ZIEWFQ
4803    VLBOML
4804    VLBOML
Name: book_ref, Length: 4805, dtype: object

In [9]:
df["passenger_id"] = df["passenger_id"].str.upper()
df["passenger_id"]

0       CN 099613273
1       AL 262446704
2       KG 715160252
3       GX 660464197
4       VT 512686120
            ...
4800    QL 541572397
4801    WT 589199597
4802    LP 465631603
4803    IB 489789417
4804    TM 882808231
Name: passenger_id, Length: 4805, dtype: object

In [10]:
df["passenger_name"] = df["passenger_name"].str.replace(r"\s+", " ", regex = True) 
df["passenger_name"]

0          Jackie Morgan
1           Brandon Cruz
2        Michael Flowers
3           Jesse Tucker
4       Michelle Richard
              ...
4800     Heather Sanchez
4801       John Campbell
4802     Gabriel Andrews
4803    Kristen Lawrence
4804       Melissa Kelly
Name: passenger_name, Length: 4805, dtype: object

In [11]:
print("Full duplicate rows: ", df.duplicated().sum())
print("Duplicate ticket_no: ", df["ticket_no"].duplicated().sum())
print("Duplicate passenger_id: ", df["passenger_id"].duplicated().sum())
df = df.drop_duplicates().drop_duplicates(subset = "ticket_no")

Full duplicate rows:  0
Duplicate ticket_no:  0
Duplicate passenger_id:  0

In [12]:
print(df["ticket_no"].str.match(r"^\d{13}$").all())
print(df["passenger_id"].str.match(r"^[A-Z]{2} \d{9}$").all())
print(df["book_ref"].str.match(r"^[A-Z0-9]{6}$").all())

True
True
True

In [13]:
print(df["outbound"].value_counts())

outbound
True     2479
False    2326
Name: count, dtype: int64

In [14]:
print(df["passenger_name"].str.match(r"^[A-Za-z .'\-]+$").all())
print()
print(df["passenger_name"].str.len().describe().round(1))
print()
print(df[df["passenger_name"] != df["passenger_name"].str.title()]["passenger_name"].head())

True

count    4805.0
mean       13.3
std         2.3
min         6.0
25%        12.0
50%        13.0
75%        15.0
max        24.0
Name: passenger_name, dtype: float64

70            Debra Lam MD
139        Stacey Jones MD
140        Marco Garza DVM
245    Christine Ritter MD
248     Dr. Jared Crane MD
Name: passenger_name, dtype: object

In [15]:
bookings = pd.read_csv(r"C:\Users\91766\Downloads\cleaned_data\5_bookings_clean.csv")

orphans = ~df["book_ref"].isin(bookings["book_ref"])
print("Tickets with unknown booking: ", orphans.sum())
df = df[~orphans]

print("Bookings with no ticket: ", (~bookings["book_ref"].isin(df["book_ref"])).sum())

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\91766\\Downloads\\cleaned_data\\5_bookings_clean.csv'

In [16]:
df.groupby("book_ref").size().value_counts().sort_index()

1    1647
2     901
3     452
Name: count, dtype: int64

In [17]:
print(df.shape, df.isnull().sum())

(4805, 5) ticket_no         0
book_ref          0
passenger_id      0
passenger_name    0
outbound          0
dtype: int64

In [18]:
print("Shape            :", df.shape)
print("Total nulls      :", df.isnull().sum().sum())
print("Duplicate rows   :", df.duplicated().sum())
print("Duplicate tickets:", df["ticket_no"].duplicated().sum())

Shape            : (4805, 5)
Total nulls      : 0
Duplicate rows   : 0
Duplicate tickets: 0

In [20]:
df = df.astype({"ticket_no": str, "book_ref": str, "passenger_id": str, "passenger_name": str, "outbound": bool})
df = df.reset_index(drop=True)
df.dtypes

ticket_no         object
book_ref          object
passenger_id      object
passenger_name    object
outbound            bool
dtype: object

In [21]:
print("Tickets          :", len(df))
print("Unique bookings  :", df["book_ref"].nunique())
print("Unique passengers:", df["passenger_id"].nunique())
print()
print(df["outbound"].value_counts(normalize=True).mul(100).round(1))
df.head()

Tickets          : 4805
Unique bookings  : 3000
Unique passengers: 4805

outbound
True     51.6
False    48.4
Name: proportion, dtype: float64

       ticket_no book_ref  passenger_id    passenger_name  outbound
0  1000000000000   OHBVRP  CN 099613273     Jackie Morgan     False
1  1000000000001   OIVGRV  AL 262446704      Brandon Cruz      True
2  1000000000002   IFLBCB  KG 715160252   Michael Flowers      True
3  1000000000003   FNOGMB  GX 660464197      Jesse Tucker     False
4  1000000000004   FNOGMB  VT 512686120  Michelle Richard     False

In [22]:
import os

out_dir = r"C:\Users\91766\Downloads\cleaned_data"
os.makedirs(out_dir, exist_ok=True)

out_path = os.path.join(out_dir, "6_tickets_clean.csv")
df.to_csv(out_path, index=False)
print("Saved to:", out_path)

Saved to: C:\Users\91766\Downloads\cleaned_data\6_tickets_clean.csv

In [23]:
check = pd.read_csv(out_path, dtype={"ticket_no": str, "book_ref": str, "passenger_id": str})

print("Shape matches :", check.shape == df.shape)
print("Data matches  :", check.equals(df))
print(check.dtypes)

Shape matches : True
Data matches  : True
ticket_no         object
book_ref          object
passenger_id      object
passenger_name    object
outbound            bool
dtype: object